<?xml version="1.0"?>
<robot name="car" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Axes are X (forward), Y (left), and Z (up).  This complies with the
       right-hand rule.  Lengths are measured in meters and masses in
       kilograms. -->

  <xacro:include filename="$(find aav_simple_description)/urdf/props.urdf.xacro"/>
  <xacro:include filename="$(find aav_simple_description)/urdf/wheel.urdf.xacro"/>

  <gazebo>
    <plugin name="pwm_steer" filename="libpwm_steer.so"/>
  </gazebo>

  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${ground_clearance + chassis_height / 2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${ground_clearance + chassis_height / 2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 ${ground_clearance + chassis_height / 2}"/>
      <mass value="2.26796"/>
      <inertia ixx=".0065806093" ixy="0" ixz="0"
        iyy=".0154882693" iyz="0" izz=".0220224112"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <xacro:front_wheel name="left" x="-1"/>
  <xacro:front_wheel name="right" x="1"/>
  <xacro:back_wheel name="left" x="-1"/>
  <xacro:back_wheel name="right" x="1"/>
</robot>

