<?xml version="1.0"?>
<robot name="car" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Axes are X (forward), Y (left), and Z (up).  This complies with the
       right-hand rule.  Lengths are measured in meters and masses in
       kilograms. -->

  <!-- The dimensions of the car body itself. -->
  <xacro:property name="chassis_length" value=".5334"/>
  <xacro:property name="chassis_width" value=".28575"/>
  <xacro:property name="chassis_height" value=".1397"/>

  <!-- The distance between the ground to the bottom of the chassis. -->
  <xacro:property name="ground_clearance" value=".05715"/>

  <!-- -->
  <xacro:property name="chassis_offset" value=".0254"/>

  <!-- The center-to-center distance between the front wheels.  (It is assumed
       that this is the same as the distance between the back wheels.) -->
  <xacro:property name="wheelbase_width" value=".2413"/>

  <!-- The distance between the front and back axes. -->
  <xacro:property name="wheelbase_length" value=".3302"/>

  <!-- The distance from the center of a wheel to the outside of its tire. -->
  <xacro:property name="tire_radius" value=".0508"/>

  <!-- The distance from the inside to the outside of a tire.  Basically, the
       width of the tread. -->
  <xacro:property name="tire_width" value=".047625"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${ground_clearance + chassis_height / 2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
  </link>

  <link name="front_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${tire_radius}" length="${tire_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <link name="front_left_link"/>

  <joint name="front_left_turn_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_link"/>
    <origin xyz="${wheelbase_length / 2} -${wheelbase_width / 2} ${tire_radius}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-.548" upper=".548" velocity=".5"/>
  </joint>

  <joint name="front_left_joint" type="continuous">
    <parent link="front_left_link"/>
    <child link="front_left_wheel"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="front_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${tire_radius}" length="${tire_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <link name="front_right_link"/>

  <joint name="front_right_turn_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_link"/>
    <origin xyz="${wheelbase_length / 2} ${wheelbase_width / 2} ${tire_radius}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-.548" upper=".548" velocity=".5"/>
  </joint>

  <joint name="front_right_joint" type="continuous">
    <parent link="front_right_link"/>
    <child link="front_right_wheel"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${tire_radius}" length="${tire_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <link name="rear_left_link"/>

  <joint name="rear_left_turn_joint" type="revolute">
    <parent link="base_link"/>
    <child link="rear_left_link"/>
    <origin xyz="-${wheelbase_length / 2} -${wheelbase_width / 2} ${tire_radius}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-.548" upper=".548" velocity=".5"/>
  </joint>

  <joint name="rear_left_joint" type="continuous">
    <parent link="rear_left_link"/>
    <child link="rear_left_wheel"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${tire_radius}" length="${tire_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <link name="rear_right_link"/>

  <joint name="rear_right_turn_joint" type="revolute">
    <parent link="base_link"/>
    <child link="rear_right_link"/>
    <origin xyz="-${wheelbase_length / 2} ${wheelbase_width / 2} ${tire_radius}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-.548" upper=".548" velocity=".5"/>
  </joint>

  <joint name="rear_right_joint" type="continuous">
    <parent link="rear_right_link"/>
    <child link="rear_right_wheel"/>
    <axis xyz="0 1 0"/>
  </joint>
</robot>

