<?xml version="1.0"?>
<robot name="wheel" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="front_wheel" params="name x">
    <link name="front_${name}_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${tire_radius}" length="${tire_width}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${tire_radius}" length="${tire_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <mass value=".5"/>
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
      </inertial>
    </link>

    <gazebo reference="front_${name}_wheel">
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <link name="front_${name}_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
      </inertial>
    </link>

    <joint name="front_${name}_turn_joint" type="revolute">
      <parent link="base_link"/>
      <child link="front_${name}_link"/>
      <origin xyz="${wheelbase_length / 2}
        ${x * wheelbase_width / 2}
        ${tire_radius}"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000" lower="-.548" upper=".548" velocity=".5"/>
    </joint>

    <joint name="front_${name}_joint" type="continuous">
      <parent link="front_${name}_link"/>
      <child link="front_${name}_wheel"/>
      <origin xyz="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="back_wheel" params="name x">
    <link name="back_${name}_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${tire_radius}" length="${tire_width}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${tire_radius}" length="${tire_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <mass value=".5"/>
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
      </inertial>
    </link>

    <gazebo reference="back_${name}_wheel">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="back_${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="back_${name}_wheel"/>
      <axis xyz="0 1 0"/>
      <origin xyz="${-wheelbase_length / 2}
        ${x * wheelbase_width / 2}
        ${tire_radius}"/>
    </joint>
  </xacro:macro>
</robot>

